### PR TITLE
Add typings for next/types

### PR DESCRIPTION
**Pull request by Ailrun**
TS typings for next/types

### CODE REVIEW

**Comment by Ailrun** [comment]
@mitchellhamilton I add this typing to share types when I types other packages.
If I don't add typing to this, I should repeat myself when I types other packages.

**Comment by mitchellhamilton** [comment]
Ok, makes sense.

I've been meaning to move the flow types into `@emotion/utils` and rename some of them for a while so I just did that, if you want to merge from master, move the types into the `@emotion/utils` and adjust them as necessary, I'll merge it.

**Comment by Ailrun** [comment]
@mitchellhamilton Then I will do that after you move those types. Close this based on what you said. Thank you for reviewing!

**Comment by mitchellhamilton** [comment]
I've already moved them.

**Comment by Ailrun** [comment]
Oh, I misunderstood your previous comment. Thank you for correcting me! I will type `@emotion/utils` and send a PR!

**Pull request closed without merging**
